name: lingua_visual
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  dio: ^5.4.1
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  cached_network_image: ^3.3.1
  intl: ^0.17.0
  shared_preferences: ^2.2.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  flutter_dotenv: ^5.2.1
  flutter_card_swiper: ^7.0.2
  webview_flutter: ^4.7.0
  flutter_hooks: ^0.21.2
  connectivity_plus: ^6.1.4
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.14.3
  # multi_language_srs:
  #   git:
  #     url: https://github.com/Dev21Maker/MultiSRS.git
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
