name: lingua_visual
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  dio: ^5.4.1
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  cached_network_image: ^3.3.1
  intl: ^0.17.0
  shared_preferences: ^2.2.2
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.7.7
  flutter_dotenv: ^5.2.1
  flutter_card_swiper: ^7.0.2
  webview_flutter: ^4.7.0
  flutter_hooks: ^0.21.2
  connectivity_plus: ^4.0.1
  multi_language_srs:
    git:
      url: https://github.com/Dev21Maker/MultiSRS.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
